import java.util.*;

class Solution {
    public boolean isBipartite(int[][] graph) {
            int n = graph.length;
                    int[] color = new int[n]; // 0 = uncolored, 1 = red, -1 = blue

                            for (int i = 0; i < n; i++) {
                                        if (color[i] == 0) { // not colored yet → start BFS
                                                        Queue<Integer> queue = new LinkedList<>();
                                                                        queue.offer(i);
                                                                                        color[i] = 1; // assign first color

                                                                                                        while (!queue.isEmpty()) {
                                                                                                                            int node = queue.poll();
                                                                                                                                                for (int neighbor : graph[node]) {
                                                                                                                                                                        if (color[neighbor] == 0) {
                                                                                                                                                                                                    // Assign opposite color
                                                                                                                                                                                                                                color[neighbor] = -color[node];
                                                                                                                                                                                                                                                            queue.offer(neighbor);
                                                                                                                                                                                                                                                                                    } else if (color[neighbor] == color[node]) {
                                                                                                                                                                                                                                                                                                                // Conflict found → not bipartite
                                                                                                                                                                                                                                                                                                                                            return false;
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                        